# Generated by Django 5.1 on 2024-10-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=30)),
                ('nameUser', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=18)),
                ('fecNacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id_consola', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreConsola', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=30)),
                ('direccionProveedor', models.CharField(max_length=50)),
                ('correoProvedor', models.CharField(max_length=40)),
                ('numeroProveedor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_juego', models.CharField(max_length=10)),
                ('nombreJuego', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('id_consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consola')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('hora_venta', models.TimeField()),
                ('monto_venta', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('id_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.juegos')),
            ],
        ),
    ]
