# Generated by Django 5.1 on 2024-09-16 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('hora_venta', models.TimeField()),
                ('monto_venta', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id_consola', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreConsola', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=30)),
                ('direccionProveedor', models.CharField(max_length=50)),
                ('correoProvedor', models.CharField(max_length=40)),
                ('numeroProveedor', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='Id de categoria'),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=30)),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=18)),
                ('fechaNac', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_juego', models.CharField(max_length=10)),
                ('nombreJuego', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('id_consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consola')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='id_juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.juegos'),
        ),
    ]
