# Generated by Django 5.1 on 2024-09-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_compra_consola_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='id_compra',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria'),
        ),
    ]
