# Generated by Django 5.1 on 2024-09-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cuenta_id_compra_alter_categoria_id_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='fechaNac',
            new_name='fecNacimiento',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='nombreUsuario',
            new_name='nameUser',
        ),
    ]
